all: c cpp d java rust scala

include ../.base/c.mk
include ../.base/cpp.mk
include ../.base/d.mk
include ../.base/java.mk
include ../.base/rust.mk
include ../.base/scala.mk
include ../.base/commontargets.mk
